import 'package:flutter/material.dart';
import 'package:flutterapp/lms_20appapp/generatedframe2widget/generated/GeneratedCoverScreenWidget.dart';

/* Frame Frame 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Image.asset(
                "assets/images/75b85294424d87090829d68a3826e08507df7ed3.png",
                color: null,
                fit: BoxFit.cover,
                width: 375.0,
                height: 812.0,
                colorBlendMode: BlendMode.dstATop,
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 812.0,
              child: GeneratedCoverScreenWidget(),
            )
          ]),
    ));
  }
}
