import 'package:flutter/material.dart';
import 'package:flutterapp/lms_20appapp/generatedframe10widget/generated/GeneratedComponent2Widget.dart';

/* Frame Frame 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 343.0,
      height: 382.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 382.0,
              child: GeneratedComponent2Widget(),
            )
          ]),
    ));
  }
}
