import 'package:flutter/material.dart';
import 'package:flutterapp/lms_20appapp/generatedframe4973widget/generated/GeneratedComponent2Widget3.dart';

/* Frame Frame 4973
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame4973Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 343.0,
      height: 360.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 360.0,
              child: GeneratedComponent2Widget3(),
            )
          ]),
    ));
  }
}
