import 'package:flutter/material.dart';
import 'package:flutterapp/lms_20appapp/generatedframe4969widget/generated/GeneratedComponent2Widget2.dart';

/* Frame Frame 4969
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame4969Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 343.0,
      height: 360.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 360.0,
              child: GeneratedComponent2Widget2(),
            )
          ]),
    ));
  }
}
