import 'package:flutter/material.dart';
import 'package:flutterapp/lms_20appapp/generatedframe4961widget/generated/GeneratedSubjectsWidget1.dart';

/* Frame Frame 4961
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame4961Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedFrame4962Widget'),
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedSubjectsWidget1(),
              )
            ]),
      ),
    ));
  }
}
