import 'package:flutter/material.dart';
import 'package:flutterapp/lms_20appapp/generatedframe4960widget/generated/GeneratedCourseScreenWidget1.dart';

/* Frame Frame 4960
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame4960Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      return SingleChildScrollView(
        scrollDirection: Axis.vertical,
        child: Container(
            height: 1045.0,
            child: Stack(children: [
              Container(
                  width: constraints.maxWidth,
                  child: Container(
                    width: 375.0,
                    height: 1045.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 375.0,
                            height: 1045.0,
                            child: GeneratedCourseScreenWidget1(),
                          )
                        ]),
                  ))
            ])),
      );
    }));
  }
}
